### ISSUE TITLE
Run the main.py script in staging and generate kibana logs

### ISSUE THREAD

**Issue by harisang** [cowprotocol/ebbo#2]
Opening this issue so that we can coordinate on the next steps. Once [this](https://github.com/cowprotocol/ebbo/pull/1) PR is merged, we would like to run the main.py daemon in staging in our backend infrastructure and transform all the messages that the daemon is printing into kibana logs.

Could @sunce86 and @ahhda describe here what needs to be done and coordinate with @shubhagarwal03 on this?

**Comment by sunce86** [comment]
Here are a few tasks:

- [ ] Add cla.yaml, pull-request.yaml, deploy.yaml so we can generate the image for each release.
- [ ] Add deployment.yaml configuration to our staging gitlab repo
- [ ] For logging ispect how it was done [in this python project](https://github.com/cowprotocol/solver-rewards) and do similar
